import type { UITypeConfig } from '../types';

export const dashboardConfig: UITypeConfig = {
  type: 'dashboard',
  label: 'Dashboard',
  icon: 'LayoutDashboard',
  description: 'Generate prompts for admin panels, analytics dashboards, and data-centric interfaces',
  configOptions: [
    {
      id: 'dashboardType',
      label: 'Dashboard Type',
      type: 'select',
      options: [
        'Analytics Dashboard',
        'AI-Powered Analytics',
        'Real-Time Operations',
        'Admin Panel',
        'CRM Dashboard',
        'Project Management',
        'E-commerce Admin',
        'Financial Dashboard',
        'Healthcare Dashboard',
        'Social Media Dashboard',
      ],
      defaultValue: 'Analytics Dashboard',
      description: 'Primary purpose of the dashboard',
    },
    {
      id: 'layout',
      label: 'Layout Style',
      type: 'select',
      options: [
        'Bento Grid',
        'AI-Personalized Layout',
        'Card-Based',
        'Traditional Grid',
        'Floating Widget System',
        'Full-Width Sections',
        'Timeline View',
        'Kanban Board Style',
        'Masonry',
      ],
      defaultValue: 'Bento Grid',
      description: 'Dashboard content arrangement style',
    },
    {
      id: 'dataVisualization',
      label: 'Data Visualization Components',
      type: 'multiSelect',
      options: [
        'Line Charts',
        'Bar Charts',
        'Pie Charts',
        'Area Charts',
        'Heatmaps',
        'Data Tables',
        'KPI Cards',
        'Progress Bars',
        'Sparklines',
        'Gauges',
      ],
      defaultValue: ['Line Charts', 'KPI Cards', 'Data Tables'],
      description: 'Types of data visualization to include',
    },
    {
      id: 'sidebarStyle',
      label: 'Navigation Style',
      type: 'select',
      options: [
        'Fixed Sidebar',
        'Collapsible Sidebar',
        'Top Navigation Bar',
        'Hybrid (Top + Side)',
        'Mini Sidebar (Icons Only)',
      ],
      defaultValue: 'Collapsible Sidebar',
      description: 'Navigation layout and behavior',
    },
    {
      id: 'theme',
      label: 'Theme',
      type: 'select',
      options: [
        'Light Mode',
        'Dark Mode',
        'Auto (System Preference)',
        'Custom Brand Theme',
      ],
      defaultValue: 'Dark Mode',
      description: 'Color theme preference',
    },
    {
      id: 'density',
      label: 'Information Density',
      type: 'select',
      options: [
        'Compact (Maximum Data)',
        'Comfortable (Balanced)',
        'Spacious (Minimal)',
      ],
      defaultValue: 'Comfortable (Balanced)',
      description: 'Amount of information displayed per screen',
    },
    {
      id: 'features',
      label: 'Key Features',
      type: 'multiSelect',
      options: [
        'AI Chatbot Interface',
        'Real-time Updates',
        'Search & Filters',
        'Predictive Analytics',
        'Custom Widgets',
        'Drill-Down Views',
        'Export Data',
        'Notifications Center',
        'User Management',
        'Settings Panel',
        'Activity Feed',
        'Reporting Tools',
        'Real-Time Collaboration',
      ],
      defaultValue: ['Search & Filters', 'Notifications Center'],
      description: 'Additional functionality to include',
    },
    {
      id: 'colorScheme',
      label: 'Color Accent',
      type: 'select',
      options: [
        'Blue (Professional)',
        'Purple (Creative)',
        'Green (Success/Health)',
        'Orange (Energy)',
        'Monochrome (Neutral)',
        'Multi-color (Data Categories)',
      ],
      defaultValue: 'Blue (Professional)',
      description: 'Primary accent color scheme',
    },
    {
      id: 'mobileFirst',
      label: 'Mobile Support',
      type: 'select',
      options: [
        'Desktop Only',
        'Responsive (Desktop + Tablet)',
        'Mobile-First (All Devices)',
      ],
      defaultValue: 'Responsive (Desktop + Tablet)',
      description: 'Mobile responsiveness level',
    },
    {
      id: 'realTimeData',
      label: 'Data Update Strategy',
      type: 'select',
      options: [
        'Real-Time (Live Updates)',
        'Near Real-Time (Every few seconds)',
        'Periodic Refresh',
        'Manual Refresh Only',
      ],
      defaultValue: 'Near Real-Time (Every few seconds)',
      description: 'How frequently data updates',
    },
    {
      id: 'accessibility',
      label: 'Accessibility',
      type: 'select',
      options: [
        'WCAG 2.2 Compliant',
        'Enhanced (Colorblind-friendly)',
        'Basic',
      ],
      defaultValue: 'WCAG 2.2 Compliant',
      description: 'Accessibility standards',
    },
    {
      id: 'performance',
      label: 'Performance Priority',
      type: 'select',
      options: [
        'Speed Optimized (Lazy Loading)',
        'Balanced',
        'Data Rich (All Widgets Load)',
      ],
      defaultValue: 'Balanced',
      description: 'Performance vs data density',
    },
  ],
};
