import type { UITypeConfig } from '../types';

export const desktopAppConfig: UITypeConfig = {
  type: 'desktopApp',
  label: 'Desktop',
  icon: 'Monitor',
  description: 'Generate prompts for desktop application designs (Electron, native apps)',
  configOptions: [
    {
      id: 'appType',
      label: 'App Type',
      type: 'select',
      options: [
        'Code Editor/IDE',
        'Design Tool',
        'Productivity Suite',
        'Communication Tool',
        'Media Player',
        'File Manager',
        'Developer Tool',
        'Creative Software',
      ],
      defaultValue: 'Productivity Suite',
    },
    {
      id: 'platform',
      label: 'Target Platform',
      type: 'select',
      options: [
        'macOS',
        'Windows',
        'Linux',
        'Cross-Platform (Electron)',
      ],
      defaultValue: 'Cross-Platform (Electron)',
    },
    {
      id: 'layoutStyle',
      label: 'Layout Style',
      type: 'select',
      options: [
        'Sidebar + Main Area',
        'Multi-Panel',
        'Bento Grid Layout',
        'Single Window',
        'Document-Based',
        'Floating Palettes',
        'Command-First (VS Code Style)',
      ],
      defaultValue: 'Sidebar + Main Area',
    },
    {
      id: 'theme',
      label: 'Theme',
      type: 'select',
      options: [
        'Light',
        'Dark',
        'System Adaptive',
        'Custom Theme',
      ],
      defaultValue: 'Dark',
    },
    {
      id: 'features',
      label: 'Key Features',
      type: 'multiSelect',
      options: [
        'Command Palette (Cmd+K)',
        'Keyboard Shortcuts',
        'Menu Bar',
        'Toolbar',
        'Status Bar',
        'Sidebar Navigation',
        'Tabs/Documents',
        'Search',
        'Settings Panel',
        'AI Assistant Integration',
        'Plugin/Extension System',
        'Real-Time Collaboration',
      ],
      defaultValue: ['Menu Bar', 'Toolbar', 'Sidebar Navigation'],
    },
    {
      id: 'complexity',
      label: 'UI Complexity',
      type: 'select',
      options: [
        'Simple & Focused',
        'Moderate',
        'Feature-Rich Pro Tool',
      ],
      defaultValue: 'Moderate',
    },
    {
      id: 'designStyle',
      label: 'Design Style',
      type: 'select',
      options: [
        'Modern (Clean, Spacious)',
        'Glassmorphism',
        'Neumorphism',
        'Professional/Enterprise',
        'Creative/Bold',
      ],
      defaultValue: 'Modern (Clean, Spacious)',
      description: 'Visual design approach',
    },
    {
      id: 'accessibility',
      label: 'Accessibility',
      type: 'select',
      options: [
        'Full Keyboard Navigation',
        'Screen Reader Support',
        'Basic',
      ],
      defaultValue: 'Full Keyboard Navigation',
      description: 'Accessibility features',
    },
    {
      id: 'performance',
      label: 'Performance',
      type: 'select',
      options: [
        'Speed Optimized',
        'Balanced',
        'Feature Rich',
      ],
      defaultValue: 'Balanced',
      description: 'Performance priority',
    },
  ],
};
