import type { UITypeConfig } from '../types';

export const mobileAppConfig: UITypeConfig = {
  type: 'mobileApp',
  label: 'Mobile',
  icon: 'Smartphone',
  description: 'Generate prompts for iOS and Android mobile application designs',
  configOptions: [
    {
      id: 'appType',
      label: 'App Type',
      type: 'select',
      options: [
        'Social Media',
        'E-commerce',
        'Productivity',
        'Finance/Banking',
        'Health & Fitness',
        'Food Delivery',
        'Travel & Booking',
        'News & Media',
      ],
      defaultValue: 'Productivity',
    },
    {
      id: 'platform',
      label: 'Platform Design',
      type: 'select',
      options: [
        'iOS 18 Style',
        'Android (Material You)',
        'Cross-Platform (Unified)',
        'Spatial UI (Vision Pro Inspired)',
      ],
      defaultValue: 'Cross-Platform (Unified)',
    },
    {
      id: 'navigationPattern',
      label: 'Navigation Pattern',
      type: 'select',
      options: [
        'Bottom Tab Bar',
        'Side Drawer/Hamburger',
        'Top Tabs',
        'Gesture-Based',
        'Hybrid',
      ],
      defaultValue: 'Bottom Tab Bar',
    },
    {
      id: 'screens',
      label: 'Key Screens',
      type: 'multiSelect',
      options: [
        'Onboarding',
        'Login/Signup',
        'Home/Dashboard',
        'Profile',
        'Settings',
        'Search',
        'Detail View',
        'List/Feed',
        'Cart/Checkout',
        'Notifications',
      ],
      defaultValue: ['Onboarding', 'Home/Dashboard', 'Profile'],
    },
    {
      id: 'designStyle',
      label: 'Design Style',
      type: 'select',
      options: [
        'Modern & Clean',
        'Glassmorphism',
        'Neumorphism',
        'Bold & Colorful (2025)',
        'Gradient Heavy',
        'Dark Mode First',
        'Minimal',
        'Bento Card Layout',
      ],
      defaultValue: 'Modern & Clean',
    },
    {
      id: 'interactions',
      label: 'Interactions',
      type: 'multiSelect',
      options: [
        'Swipe Gestures',
        'Pull to Refresh',
        'Haptic Feedback',
        'Animations & Transitions',
        'Bottom Sheets',
        'Floating Action Button',
        'Thumb-Zone Optimization',
        'One-Handed Mode',
        'Gesture-Based Controls',
        'Voice Commands',
      ],
      defaultValue: ['Pull to Refresh', 'Animations & Transitions'],
    },
    {
      id: 'darkMode',
      label: 'Theme Mode',
      type: 'select',
      options: [
        'Light Only',
        'Dark Only',
        'System Adaptive',
        'User Toggle',
      ],
      defaultValue: 'System Adaptive',
      description: 'App theme options',
    },
    {
      id: 'accessibility',
      label: 'Accessibility',
      type: 'select',
      options: [
        'WCAG 2.2 AAA',
        'Standard (AA)',
        'Basic',
      ],
      defaultValue: 'Standard (AA)',
      description: 'Accessibility level',
    },
    {
      id: 'aiFeatures',
      label: 'AI Features',
      type: 'multiSelect',
      options: [
        'AI Assistant/Chatbot',
        'Smart Suggestions',
        'Voice Interface',
        'Personalization Engine',
        'None',
      ],
      defaultValue: ['None'],
      description: 'AI-powered capabilities',
    },
    {
      id: 'performance',
      label: 'Performance Focus',
      type: 'select',
      options: [
        'Speed First (Minimal Animations)',
        'Balanced',
        'Rich Experience (Heavy Animations)',
      ],
      defaultValue: 'Balanced',
      description: 'Performance vs visual richness',
    },
  ],
};
