import type { UITypeConfig } from '../types';

export const websiteConfig: UITypeConfig = {
  type: 'website',
  label: 'Website',
  icon: 'Globe',
  description: 'Generate prompts for website designs - landing pages, e-commerce, portfolios, and more',
  configOptions: [
    {
      id: 'websiteType',
      label: 'Website Type',
      type: 'select',
      options: [
        'E-commerce Storefront',
        'Landing Page',
        'Portfolio',
        'Blog',
        'Corporate Website',
        'SaaS Product',
        'Marketing Website',
        'Community Platform',
      ],
      defaultValue: 'Landing Page',
      description: 'The primary purpose of the website',
    },
    {
      id: 'layout',
      label: 'Layout Structure',
      type: 'select',
      options: [
        'Single Page',
        'Multi Page',
        'Bento Grid',
        'Grid Layout',
        'Asymmetric Layout',
        'Floating/Layered Elements',
        'Organic Shapes Layout',
        'Full-Bleed Sections',
        'Scroll-Driven Layout',
      ],
      defaultValue: 'Single Page',
      description: 'Overall page structure and organization',
    },
    {
      id: 'aestheticStyle',
      label: 'Aesthetic Style',
      type: 'select',
      options: [
        'Modern Clean',
        'Portfolio Minimalist (Glass)',
        'Enhanced Minimalism (2025)',
        'Glassmorphism',
        'Neumorphism/Soft UI',
        'Claymorphism',
        'Brutalist',
        'Y2K/Retro Futurism',
        'Kinetic Typography',
        '3D Immersive',
        'Material Design',
        'Gradient & Vibrant',
        'Dark & Moody',
      ],
      defaultValue: 'Modern Clean',
      description: 'Visual design aesthetic',
    },
    {
      id: 'components',
      label: 'Included Components',
      type: 'multiSelect',
      options: [
        'Header/Navigation',
        'Hero Section',
        'Feature Cards',
        'Testimonials',
        'Pricing Table',
        'FAQ Accordion',
        'Contact Form',
        'Newsletter',
        'Footer',
        'Logo Wall',
        'CTA Sections',
        'Image Gallery',
      ],
      defaultValue: ['Header/Navigation', 'Hero Section', 'Footer'],
      description: 'Components to include in the design',
    },
    {
      id: 'copywritingTone',
      label: 'Copywriting Tone',
      type: 'select',
      options: [
        'Professional & Trustworthy',
        'Friendly & Conversational',
        'Casual & Fun',
        'Formal & Corporate',
        'Technical & Detailed',
        'Creative & Bold',
        'Benefit-Driven & Persuasive',
      ],
      defaultValue: 'Professional & Trustworthy',
      description: 'Tone of voice for copy and messaging',
    },
    {
      id: 'interactivity',
      label: 'Interactivity Level',
      type: 'select',
      options: [
        'Static',
        'Micro-interactions Only',
        'Basic Animations (Hover, Fade)',
        'Scroll Animations (Parallax)',
        'Custom Cursor Effects',
        '3D Elements & Animations',
        'Highly Interactive (Full Experience)',
      ],
      defaultValue: 'Basic Animations (Hover, Fade)',
      description: 'Level of motion and interactivity',
    },
    {
      id: 'colorScheme',
      label: 'Color Scheme',
      type: 'select',
      options: [
        'Vibrant & Bold (2025 Trend)',
        'Brand Colors',
        'Monochrome (Black & White)',
        'Pastel & Soft',
        'Earth Tones',
        'Blue & Professional',
        'Gradient Heavy',
      ],
      defaultValue: 'Brand Colors',
      description: 'Overall color palette',
    },
    {
      id: 'darkMode',
      label: 'Dark Mode',
      type: 'select',
      options: [
        'Light Only',
        'Dark Only',
        'System Adaptive (Auto)',
        'Toggle Available',
      ],
      defaultValue: 'System Adaptive (Auto)',
      description: 'Dark mode support',
    },
    {
      id: 'accessibility',
      label: 'Accessibility Level',
      type: 'select',
      options: [
        'WCAG 2.1 AA (Standard)',
        'WCAG 2.2 AAA (Enhanced)',
        'Basic',
      ],
      defaultValue: 'WCAG 2.1 AA (Standard)',
      description: 'Accessibility compliance level',
    },
    {
      id: 'aiFeatures',
      label: 'AI Features',
      type: 'multiSelect',
      options: [
        'AI Chatbot',
        'Smart Recommendations',
        'Voice Interface',
        'Personalization',
        'None',
      ],
      defaultValue: ['None'],
      description: 'AI-powered features to include',
    },
    {
      id: 'performance',
      label: 'Performance Priority',
      type: 'select',
      options: [
        'Speed Optimized',
        'Balanced',
        'Feature Rich',
      ],
      defaultValue: 'Balanced',
      description: 'Performance vs features balance',
    },
  ],
};
